######################################################################
# Automatically generated by qmake (3.1) Mon Dec 19 18:10:01 2022
######################################################################

TEMPLATE = app
QT += widgets
HEADERS += ButtonWindow.h
SOURCES += ButtonWindow.cpp
# Directories
